### ISSUE TITLE
Unusable since Mod version 2.0 (Fabric 0.15.0 & 0.14.25 | MC 1.20.2)

### ISSUE THREAD

**Issue by spikehidden** [dooji2/resource-pack-downloader#2]
The mod seems to load (Visible in the log and Modmenu) but does nothing. I also found the following error in the startup log:
```
[01:13:17] [Render thread/INFO]: [STDERR]: java.lang.ClassCastException: class com.google.gson.JsonPrimitive cannot be cast to class com.google.gson.JsonArray (com.google.gson.JsonPrimitive and com.google.gson.JsonArray are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @553f17c)
[01:13:17] [Render thread/INFO]: [STDERR]: 	at com.google.gson.JsonObject.getAsJsonArray(JsonObject.java:209)
[01:13:17] [Render thread/INFO]: [STDERR]: 	at com.dooji.rpdl.RPDL.onInitialize(RPDL.java:76)
[01:13:17] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
[01:13:17] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[01:13:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:466)
[01:13:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:214)
[01:13:17] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[01:13:17] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[01:13:17] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

If you need more info let me know.

**Comment by dooji2** [comment]
Hmm could you send me your pack.json file? Especially what kind of URLs you've put for it to download from

**Comment by antonwnk** [comment]
When is fix coming?

**Comment by dooji2** [comment]
Closed due to inactivity
